# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    build: .
    volumes:
      - .:/app
    entrypoint: ["flask", "run"]
  db:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
      - "33060:33060" 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: food_expense_tracker
