# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
      - "33060:33060" 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
