import os

SQLALCHEMY_DATABASE_URI = os.environ.get('CONFIG_SQLALCHEMY_DATABASE_URI')
SECRET_AES_KEY = os.environ.get('CONFIG_SQLALCHEMY_DATABASE_FEILD_AES_KEY')
JWT_SECRET_KEY = os.environ.get('CONFIG_JWT_SECRET_KEY')